### ISSUE TITLE
android version it show error

### ISSUE THREAD

**Issue by abuammar** [master-atul/react-native-appstore-version-checker#11]
:react-native-appstore-version-checker:compileReleaseJavaWithJavac
/Users/ws1/Code/mobile/node_modules/react-native-appstore-version-checker/android/src/main/java/com/masteratul/RNAppstoreVersionCheckerPackage.java:13: error: RNAppstoreVersionCheckerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNAppstoreVersionCheckerPackage implements ReactPackage {
       ^
1 error
:react-native-appstore-version-checker:compileReleaseJavaWithJavac FAILED

**Comment by master-atul** [comment]
Which version of react native are you using @abuammar  ?

**Comment by master-atul** [comment]
Hi @abuammar  Just release v2.5.0 with support for older version of React Native (v0.47 or less). This should fix your problem.

**Comment by abuammar** [comment]
"react-native": "^0.33.1"
