### ISSUE TITLE
Error: more than one library with package name 'com.reactlibrary'

### ISSUE THREAD

**Issue by Skylnt** [master-atul/react-native-appstore-version-checker#4]
when add import com.reactlibrary.RNAppstoreVersionCheckerPackage in MainApplication.
but in MainApplication had 
import com.reactlibrary.RNCardViewPackage;
Error 'com.reactlibrary'.
Help me.

**Comment by master-atul** [comment]
Hi @Skylnt I just release a patch version with the fix. Version 2.2 solves this issue. 
Please  do 
1.`react-native unlink react-native-appstore-version-checker ` 
2. `yarn remove react-native-appstore-version-checker`
3. `yarn add react-native-appstore-version-checker`
4. `react-native link react-native-appstore-version-checker`

**Comment by master-atul** [comment]
closing this .. please open it up if you face any issues. Thanks.

**Comment by Skylnt** [comment]
Thankyou very much,
Thanks, support. ^^.
