### ISSUE TITLE
Android is not returning the appstore version number

### ISSUE THREAD

**Issue by parth19** [master-atul/react-native-appstore-version-checker#8]
Hi,

While trying to get the playsotre version number for an app, it returns "" as response.
I checked JS and native code already.

My initial suspection is probably google has changed the jQueryselector from "softwareVersion" to something else.

Can you please check and let me know.

Let me know if any other information is required.

**Comment by datvtwakumo** [comment]
Me too

**Comment by master-atul** [comment]
Will take a look @parth19  @datvtwakumo  and return back.  Meanwhile you can use the custom query selector for working with it. Will release a patch soon .

**Comment by master-atul** [comment]
@parth19  @datvtwakumo  Version 2.4.0 has the fix for recent play store change.

Nothing to do . Just upgrade the package and use it
the default way

```getAppstoreAppVersion('com.supercell.clashofclans') //put any apps packageId here
.then((appVersion) => {
  console.log('clashofclans android app version on playstore', appVersion);
})
.catch((err) => {
  console.log('error occurred', err);
});```
